version: '3.8'

services:
  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9191:9191"
    links:
      - service-registry
    depends_on:
      - service-registry
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka

  complaints-system-craft-mock:
    build:
      context: ./complaints-system-craft-mock
    ports:
      - "8081:8081"

  complaint-service:
    build:
      context: ./complaint-service
    environment:
      user.service.url: http://host.docker.internal:8081/users/
      purchase.service.url: http://host.docker.internal:8081/purchases/
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka
    ports:
      - "8082:8082"
    links:
      - service-registry
      - config-server
      - complaints-system-craft-mock
    depends_on:
      - service-registry
      - config-server
      - complaints-system-craft-mock
