version: '3.8'

services:
  complaints-system-craft-mock:
    build:
      context: ./complaints-system-craft-mock
    ports:
      - "8081:8081"

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA.INSTANCE.CLIENT.SERVERURL.DEFAULTZONE=http://host.docker.internal:8761/eureka/
    ports:
      - "9191:9191"
    depends_on:
      - service-registry

  complaint-service:
    build:
      context: ./complaint-service
    environment:
      - USER_SERVICE_URL=http://host.docker.internal:8081/users/
      - PURCHASE_SERVICE_URL=http://host.docker.internal:8081/purchases/
    ports:
      - "8082:8082"
    depends_on:
      - complaints-system-craft-mock
